#!/bin/sh
#
# The development docker image runs this script by default to start
# the application. To start the docker container for development, use
# ./docker/app
#
# Before the command is run, "./docker/entrypoint" is run to setup the
# configuration (and maybe other things in the future).

set -e

while [ ! -e ./combust/bin/httpd ]; do
    echo waiting for code to be synced
    sleep 2
done


exec ./combust/bin/httpd
