FROM harbor.ntppool.org/ntppool/base-os@sha256:14b36683bbdf8c03429b9b338dba0c1d405fc72857a3a495c5500190d7904697
USER root

RUN apk -U --no-cache upgrade

ENV BUILD 20231126
RUN cpanm Net::Async::HTTP::Server Plack::Handler::Net::Async::HTTP::Server Plack::Middleware::Headers
RUN cpanm OpenTelemetry OpenTelemetry::SDK OpenTelemetry::Exporter::OTLP Plack::Middleware::OpenTelemetry
#RUN cpanm https://tmp.askask.com/2023/12/Plack-Middleware-OpenTelemetry-0.233370-TRIAL.tar.gz
RUN cpanm https://tmp.askask.com/2023/12/Net-Async-HTTP-Server-0.14.tar.gz

USER root

ENV CBCONFIG=
ENV HULK /usr/bin/hulk

WORKDIR /ntppool

EXPOSE 8299
ENTRYPOINT ["./docker/entrypoint"]
CMD ["./docker-run"]

RUN mkdir /var/ntppool data && chown ntppool:ntppool data /var/ntppool
RUN rm -fr docs/ntppool/_syndicate && \
    mkdir -p data/syndicate docs/ntppool && \
    ln -s /ntppool/data/syndicate docs/ntppool/_syndicate && \
    chown -R ntppool:ntppool data docs/ntppool/_syndicate

ADD --chown=ntppool . /ntppool

USER ntppool
