FROM harbor.ntppool.org/ntppool/base-os:3.19.0-1
#FROM harbor.ntppool.org/ntppool/base-os@sha256:0e2e854c256547417439128e6754c82d4b32a06a4298b3c585c1dbfb62b300fc
USER root

#RUN apk -U --no-cache upgrade

ENV BUILD 20231126
RUN cpanm Net::Async::HTTP::Server Plack::Handler::Net::Async::HTTP::Server Plack::Middleware::Headers
RUN cpanm OpenTelemetry OpenTelemetry::SDK OpenTelemetry::Exporter::OTLP Plack::Middleware::OpenTelemetry
#RUN cpanm https://tmp.askask.com/2024/01/Plack-Middleware-OpenTelemetry-0.240030.tar.gz
#RUN cpanm https://tmp.askask.com/2023/12/Net-Async-HTTP-Server-0.14.tar.gz
RUN cpanm -v https://tmp.askask.com/2024/02/Net-Async-HTTP-Server-0.14bis2.tar.gz

USER root

ENV CBCONFIG=
ENV HULK /usr/bin/hulk

WORKDIR /ntppool

EXPOSE 8299
ENTRYPOINT ["./docker/entrypoint"]
CMD ["./docker-run"]

RUN mkdir /var/ntppool data && chown ntppool:ntppool data /var/ntppool
RUN rm -fr docs/ntppool/_syndicate && \
    mkdir -p data/syndicate docs/ntppool && \
    ln -s /ntppool/data/syndicate docs/ntppool/_syndicate && \
    chown -R ntppool:ntppool data docs/ntppool/_syndicate

ADD --chown=ntppool . /ntppool

USER ntppool
