#!/bin/sh

set -e

rm -f .nospin.start

app="$@"

if [ "$app" == "" ]; then
  app=./docker-run
  ports="-p 8299:8299"
fi

IMAGE=harbor.ntppool.org/ntppool/ntppool:main

tparm=""

if [ -t 0 ]; then
    tparm="-t -i"
fi

docker pull $IMAGE

docker run $tparm \
 -v $(pwd):/ntppool \
 --env-file=ntppool.env \
 --network ntppool_default \
 $ports \
 --rm \
 $IMAGE ./docker/entrypoint $app
