#!/bin/sh
set -e

if [ -z $CBROOT ]; then
  export CBROOTLOCAL=`pwd`
  export CBROOT=$CBROOTLOCAL/combust
fi

fastly_ips=/etc/fastly-ips/fastly.json

if [ -e $fastly_ips ]; then
  export proxyip_forwarders=`jq -cr '[.ipv6_addresses, .addresses] | flatten | join(", ") ' < $fastly_ips`
fi

while [ ! -e combust.conf.tmpl ]; do
    echo "waiting for code to be synced"
    sleep 2
done

if [ -z "$CBCONFIG" ]; then
    export CBCONFIG=`mktemp -d`/combust.conf
fi

gomplate -f combust.conf.tmpl -o $CBCONFIG

set -x

exec "$@"
