#!/bin/sh
set -e

if [ -z $CBROOT ]; then
  export CBROOTLOCAL=`pwd`
  export CBROOT=$CBROOTLOCAL/combust
fi

confd -onetime -confdir=confd -backend env -log-level warning
export CBCONFIG=/var/ntppool/combust.conf

set -x

exec "$@"
