# GENERATED CODE - DO NOT EDIT
# Generated from: ntppool/account/v1/account.proto
# Generator: protoc-gen-perl-capi v0.1.0

package NP::CAPI::Account;
use strict;
use warnings;
use NP::CAPI qw(connect_rpc);
use Exporter 'import';

our @EXPORT_OK = qw(
    get_account_status
);

=head1 NAME

NP::CAPI::Account - ConnectRPC client for AccountService

=head1 SYNOPSIS

    use NP::CAPI::Account qw(get_account_status);
    # GetAccountStatus returns the current monitor eligibility and status for an account.
Authentication is handled by middleware - the account is extracted from the session context.
    my $result = get_account_status(
        auth    => $user_token,
        account => $account_token,
        context => $request_context,
    );


=head1 DESCRIPTION

Auto-generated ConnectRPC client for ntppool.account.v1.AccountService.

This module provides Perl wrappers for calling AccountService RPC methods
over HTTP using the ConnectRPC protocol.

=head1 METHODS


=head2 get_account_status

GetAccountStatus returns the current monitor eligibility and status for an account.
Authentication is handled by middleware - the account is extracted from the session context.

B<Arguments:>

    my $result = get_account_status(
        auth    => $user_token,      # Optional: User/session authentication token
        account => $account_token,   # Optional: Account selection token
        context => $request_context, # Optional: Request context for X-Forwarded-For
    );

B<Returns:>

Hashref with structure:

    {
        code         => 200,         # HTTP status code
        status_line  => "200 OK",    # HTTP status text
        connect_code => undef,       # ConnectRPC error code (or undef)
        data         => {            # Response data
            enabled => ...,      # bool - enabled indicates if the account has access to monitor features.
 True if: account has existing monitors, has verified servers for required duration,
 or has the monitor_enabled flag set.
            can_register => ...,      # bool - can_register indicates if the account can register new monitors.
 True if: enabled is true, account hasn't reached monitor limit,
 global limit not reached, and registration not disabled.
            global_limit_reached => ...,      # bool - global_limit_reached indicates if new monitor registration is blocked
 system-wide due to capacity limits. Only present when true.
            server_months => ...,      # int - server_months is the number of months servers must be verified
 before an account becomes eligible for monitors.
            monitor_count => ...,      # int - monitor_count is the current number of active monitors for this account.
            monitor_limit => ...,      # int - monitor_limit is the maximum number of monitors this account can have.
 Default is 3, but can be customized per account.
        },
        error        => undef,       # Error message (if any)
        trace_id     => "...",       # OpenTelemetry trace ID
    }

B<ConnectRPC Error Codes:>

    unauthenticated, permission_denied, internal, invalid_argument, etc.

B<Example:>

    my $result = get_account_status(
        auth    => $self->plain_cookie($self->user_cookie_name),
        account => $self->current_account->id_token,
        context => $self->_get_request_context(),
    );

    if ($result->{error}) {
        warn "Error: $result->{error}";
    } else {
        my $data = $result->{data};
        # Use response fields...
    }

=cut

sub get_account_status {
    my %args = @_;

    # Extract request fields from args
    my %request = ();

    return connect_rpc(
        service => 'ntppool.account.v1.AccountService',
        method  => 'GetAccountStatus',
        request => \%request,
        %args  # Pass through auth, account, context
    );
}



1;

__END__

=head1 GENERATED

This module was auto-generated by protoc-gen-perl-capi from ntppool/account/v1/account.proto.

DO NOT EDIT THIS FILE MANUALLY.

=head1 SEE ALSO

L<NP::CAPI>

=cut
