
INSERT INTO `zones` VALUES (1,'europe','Europe',49);
INSERT INTO `zones` VALUES (2,'asia','Asia',49);
INSERT INTO `zones` VALUES (3,'oceania','Oceania',49);
INSERT INTO `zones` VALUES (4,'north-america','North America',49);
INSERT INTO `zones` VALUES (5,'at','Austria',1);
INSERT INTO `zones` VALUES (6,'au','Australia',3);
INSERT INTO `zones` VALUES (7,'ca','Canada',4);
INSERT INTO `zones` VALUES (8,'ch','Switzerland',1);
INSERT INTO `zones` VALUES (9,'de','Germany',1);
INSERT INTO `zones` VALUES (10,'dk','Denmark',1);
INSERT INTO `zones` VALUES (11,'es','Spain',1);
INSERT INTO `zones` VALUES (12,'fr','France',1);
INSERT INTO `zones` VALUES (13,'it','Italy',1);
INSERT INTO `zones` VALUES (14,'lu','Luxembourg',1);
INSERT INTO `zones` VALUES (15,'nl','Netherlands',1);
INSERT INTO `zones` VALUES (16,'no','Norway',1);
INSERT INTO `zones` VALUES (17,'nz','New Zealand',3);
INSERT INTO `zones` VALUES (18,'ph','Philippines',2);
INSERT INTO `zones` VALUES (19,'pl','Poland',1);
INSERT INTO `zones` VALUES (20,'se','Sweden',1);
INSERT INTO `zones` VALUES (21,'si','Slovenia',1);
INSERT INTO `zones` VALUES (22,'uk','United Kingdom',1);
INSERT INTO `zones` VALUES (23,'us','United States',4);
INSERT INTO `zones` VALUES (24,'my','Malaysia',2);
INSERT INTO `zones` VALUES (25,'mx','Mexico',4);
INSERT INTO `zones` VALUES (26,'fi','Finland',1);
INSERT INTO `zones` VALUES (27,'ie','Ireland',1);
INSERT INTO `zones` VALUES (28,'br','Brazil',29);
INSERT INTO `zones` VALUES (29,'south-america','South America',49);
INSERT INTO `zones` VALUES (30,'ru','Russian Federation',1);
INSERT INTO `zones` VALUES (31,'tr','Turkey',2);
INSERT INTO `zones` VALUES (32,'sg','Singapore',2);
INSERT INTO `zones` VALUES (33,'cl','Chile',29);
INSERT INTO `zones` VALUES (34,'in','India',2);
INSERT INTO `zones` VALUES (35,'hk','Hong Kong',2);
INSERT INTO `zones` VALUES (36,'ae','United Arab Emirates',2);
INSERT INTO `zones` VALUES (37,'be','Belgium',1);
INSERT INTO `zones` VALUES (38,'pt','Portugal',1);
INSERT INTO `zones` VALUES (39,'jp','Japan',2);
INSERT INTO `zones` VALUES (40,'gt','Guatemala',4);
INSERT INTO `zones` VALUES (41,'bd','Bangladesh',2);
INSERT INTO `zones` VALUES (42,'il','Israel',2);
INSERT INTO `zones` VALUES (43,'kr','Korea',2);
INSERT INTO `zones` VALUES (44,'gr','Greece',1);
INSERT INTO `zones` VALUES (45,'hu','Hungary',1);
INSERT INTO `zones` VALUES (46,'bg','Bulgaria',1);
INSERT INTO `zones` VALUES (47,'th','Thailand',2);
INSERT INTO `zones` VALUES (48,'ro','Romania',1);
INSERT INTO `zones` VALUES (49,'@','Global',NULL);
INSERT INTO `zones` VALUES (53,'cz','Czech Republic',1);
INSERT INTO `zones` VALUES (54,'ir','Iran',2);
INSERT INTO `zones` VALUES (55,'africa','Africa',49);
INSERT INTO `zones` VALUES (56,'yu','Yugoslavia',1);
INSERT INTO `zones` VALUES (57,'tz','Tanzania',55);
INSERT INTO `zones` VALUES (58,'tw','Taiwan',2);
INSERT INTO `zones` VALUES (59,'za','South Africa',55);

