#!/bin/bash
exec </dev/null
exec 2>&1
find .nospin.start -mmin -1 -exec echo "*** rate limiting restart ***" \; -exec sleep 2 \;
touch .nospin.start
cd ~/ntppool
. cbsetup
echo Starting
export PERL_LWP_SSL_VERIFY_HOSTNAME=0
# init_perlbrew forces the program to under under the perlbrew environment, the
# script from production is listed below
exec init_perlbrew ./combust/bin/httpd
exit 2

## 
## example init_perlbrew script
##
#!/bin/bash

export PERLBREW_ROOT=/opt/perlbrew
if [ -e $PERLBREW_ROOT/etc/bashrc ]; then
    source $PERLBREW_ROOT/etc/bashrc
fi

if [[ ! -z "$@" ]]; then
    exec "$@"
fi